name: MLflow CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Mengizinkan eksekusi manual

# Mendefinisikan env lokal agar MLflow tahu di mana mencari artefak run
env:
  MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns

jobs:
  build-and-push:
    name: Train, Build, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install MLflow
        run: |
          pip install mlflow==2.19.0 virtualenv

      - name: Run MLflow Project (Training Otomatis)
        run: |
          # Perintah ini akan membaca MLproject dan conda.yaml
          mlflow run .

      - name: Build Docker Image (MLflow Build-Docker)
        run: |
          # Membaca Run ID yang di-generate oleh modelling.py
          RUN_ID=$(cat run_id.txt)
          echo "Captured Run ID: $RUN_ID"
          
          # Membangun Docker Image langsung dari artefak model MLflow
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n ${{ secrets.DOCKER_USERNAME }}/sml-breast-cancer:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sml-breast-cancer:latest